config/routes.rb
Rails.application.routes.draw do
	root 'home#index', page: 'home'
	get '/tweets', to: 'tweets#index'
	get '/tweets/new', to: 'tweets#new', as: :new_tweet
	get '/tweets/:id/edit', to: 'tweets#edit', as: :edit_tweet
	get '/tweets/:id', to: 'tweets#show', as: :tweet
	post '/tweets', to: 'tweets#create'
	patch '/tweets/:id', to: 'tweets#update'
	put '/tweets/:id', to: 'tweets#update'
	delete '/tweets/:id', to: 'tweets#destroy'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController <ApplicationController

	def index
	end
	
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :set_tweet, only: [:show, :edit, :update, :destroy]

	def index
		if params[:sort]
			@tweets = Tweet.order(params[:sort])
		else
			@tweets = Tweet.all
		end
	end

	def show
	end

	def edit
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
		if @tweet.save
			redirect_to tweets_path, notice: 'Your tweet was published!'
		else
			render :new
		end
	end

	def update
		if @tweet.update_attributes(tweet_params)
			redirect_to tweets_path, notice: 'Your tweet was succesfully updated!'
		else
			render :edit
		end
	end

	def destroy
		@tweet.destroy
		redirect_to tweets_path, notice: 'Your tweet was succesfully deleted!'
	end

	private

	def set_tweet
		@tweet = Tweet.find(params[:id])
	end

	def tweet_params
		params.require(:tweet).permit(:handle, :content)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Twitter</h1>

<div class="welcome">
	<p>See what’s happening in the world right now. From breaking news and entertainment, sports and politics, to big events and everyday interests. If it’s happening anywhere, it’s happening on Twitter. Get the full story as it unfolds, with all the live commentary.</p>

	<h3><%= link_to "Let's Get Started!", tweets_path %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body class="container-fluid">

<nav class="navbar navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
      	<span><a class="navbar-brand" href="#">
        	<%= link_to image_tag("twitter_logo.png", :size => "50x50"), tweets_path %>
      	</a></span>

          <button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
             <span class="sr-only">Toggle navigation</span>
             <a href="/tweets/new"><span class="glyphicon glyphicon-pencil"></span></a>
         </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">        
          <li><%= link_to "New Tweet", new_tweet_path %></li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
 </nav>
 <hr>

<%= yield %>
</body>
</html>

app/views/tweets/_form.html.erb
<div class="container">
  <%= form_for(@tweet) do |f| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="panel panel-info">
      <div class="panel-heading">
        <strong>HANDLE</strong>
      </div>
        <%= f.text_field :handle, :class => "form-control", :required=> true %>
      <div class="panel-heading">
        <strong>CONTENT</strong>
      </div>
        <%= f.text_area :content, size:"5x5", :class => "form-control", :required => true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
      <% end %>
    </div>

app/views/tweets/edit.html.erb
<h1>Edit Your Tweet</h1>

<div class="container">
	<%= render 'form' %>

	<div class="link">
	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
	</div>
</div>

app/views/tweets/index.html.erb
<div class="jumbotron my-background">
  <div class="container-fluid">
  </div>
</div>

<p class="notice" id="notice"><%= notice %></p>

<div class="container">

<%= link_to "Sort by Handle", :sort => "handle" %> | 
<%= link_to "Sort by Date", :sort => "updated_at" %>

<h1>Welcome to Twitter</h1>


    <% @tweets.each do |tweet| %>
		<div class="panel panel-info">
		  <div class="panel-heading">
		    <div class="panel-title pull-left"><strong>@<%= link_to "#{tweet.handle}", tweet_path(tweet) %></strong></div>
		    <div class="panel-title pull-right"><%= tweet.updated_at.localtime.strftime('%d %b %Y at %l:%M:%S')%></div>
		  </div>
		  <div class="panel-body">
		    <%= tweet.content %>
		  </div>
		</div>
    <% end %>

</div>

app/views/tweets/new.html.erb
	<h1>New Tweet</h1>

<div class="container">

	<%= render 'form' %>

	<div class="link"><%= link_to 'Back', tweets_path %></div>
</div>

app/views/tweets/show.html.erb
<div class="container"
<p id="notice"><%= notice %></p>

		<div class="panel panel-info">
		<div class="panel-heading">
		  <div class="panel-title pull-left"><strong>@<%= @tweet.handle %></strong></div>
		  <div class="panel-title pull-right"><%= @tweet.updated_at.localtime.strftime('%d %b %Y at %l:%M:%S')%></div>
		</div>
		  <div class="panel-body">
		    <%= @tweet.content %>
		  </div>
		</div>

<%= link_to "Back", tweets_path %>  | 
<%= link_to "Edit", edit_tweet_path(@tweet) %>  | 
<%= link_to "Delete", tweet_path, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?"} %>
</div>